package ast

const indent = 3

var Depth int

type Worker interface {
	ActSubstrate(*SubstrateNode) Value
	ActStorageDeclList(*StorageDeclList) Value
	ActStorageDecl(*StorageDeclNode) Value
	ActStructFieldList(*StructFieldList) Value
	ActStructFieldNode(*StructFieldNode) Value
	ActStructDefList(*StructDefList) Value
	ActStructDefNode(*StructDefNode) Value
	ActEventDeclList(*EventDeclList) Value
	ActEventDecl(*EventDeclNode) Value
	ActFunctionDefList(*FunctionDefList) Value
	ActFunctionDef(*FunctionDefNode) Value
	ActFormalArgList(*FormalArgList) Value
	ActFormalArgNode(*FormalArgNode) Value
	ActTypeNameList(*TypeNameList) Value
	ActTypeName(*TypeNameNode) Value
	ActBasicType(*BasicTypeNode) Value
	ActMapType(*MapTypeNode) Value
	ActStructArgType(*StructArgTypeNode) Value
	ActArrayType(*ArrayTypeNode) Value
	ActLibraryType(*LibraryTypeNode) Value
	ActStmtBlock(*StmtBlockNode) Value
	ActStmtList(*StmtList) Value
	ActStmt(*StmtNode) Value
	ActIfStmt(*IfStmtNode) Value
	ActIf(*IfNode) Value
	ActElse(*ElseNode) Value
	ActElseIfList(*ElseIfList) Value
	ActElseIf(*ElseIfNode) Value
	ActWhile(*WhileNode) Value
	ActDoWhile(*DoWhileNode) Value
	ActContinueStmt(*ContinueStmtNode) Value
	ActBreakStmt(*BreakStmtNode) Value
	ActReturnStmt(*ReturnStmtNode) Value
	ActRequireStmt(*RequireStmtNode) Value
	ActThrowStmt(*ThrowStmtNode) Value
	ActEmitStmt(*EmitStmtNode) Value
	ActGotoStmt(*GotoStmtNode) Value
	ActCalcAssignStmt(*CalcAssignStmtNode) Value
	ActExprStmt(*ExprStmtNode) Value
	ActCastExpression(*CastExpressionNode) Value
	ActExternalCallExpr(*ExternalCallExprNode) Value
	ActExtSpecifierList(*ExtSpecifierList) Value
	ActExtSpecifier(*ExtSpecifierNode) Value
	ActExpressionList(*ExpressionList) Value
	ActExpression(*ExpressionNode) Value
	ActSubexpr(*SubexprNode) Value
	ActRvalue(*RvalueNode) Value
	ActLvalue(*LvalueNode) Value
	ActAllocSize(*AllocSizeNode) Value
	ActPrimaryList(*PrimaryList) Value
	ActPrimary(*PrimaryNode) Value
	ActToken(*TokenNode) Value
	ActFallbackStmt(*FallbackStmtNode) Value
}

func Act(w Worker, n AstNode) (v Value) {
	switch n.(type) {
	case *SubstrateNode:
		return w.ActSubstrate(n.(*SubstrateNode))
	case *StorageDeclList:
		return w.ActStorageDeclList(n.(*StorageDeclList))
	case *StorageDeclNode:
		return w.ActStorageDecl(n.(*StorageDeclNode))
	case *StructFieldList:
		return w.ActStructFieldList(n.(*StructFieldList))
	case *StructFieldNode:
		return w.ActStructFieldNode(n.(*StructFieldNode))
	case *StructDefList:
		return w.ActStructDefList(n.(*StructDefList))
	case *StructDefNode:
		return w.ActStructDefNode(n.(*StructDefNode))
	case *EventDeclList:
		return w.ActEventDeclList(n.(*EventDeclList))
	case *EventDeclNode:
		return w.ActEventDecl(n.(*EventDeclNode))
	case *FunctionDefList:
		return w.ActFunctionDefList(n.(*FunctionDefList))
	case *FunctionDefNode:
		return w.ActFunctionDef(n.(*FunctionDefNode))
	case *FormalArgList:
		return w.ActFormalArgList(n.(*FormalArgList))
	case *FormalArgNode:
		return w.ActFormalArgNode(n.(*FormalArgNode))
	case *TypeNameList:
		return w.ActTypeNameList(n.(*TypeNameList))
	case *TypeNameNode:
		return w.ActTypeName(n.(*TypeNameNode))
	case *BasicTypeNode:
		return w.ActBasicType(n.(*BasicTypeNode))
	case *MapTypeNode:
		return w.ActMapType(n.(*MapTypeNode))
	case *StructArgTypeNode:
		return w.ActStructArgType(n.(*StructArgTypeNode))
	case *ArrayTypeNode:
		return w.ActArrayType(n.(*ArrayTypeNode))
	case *LibraryTypeNode:
		return w.ActLibraryType(n.(*LibraryTypeNode))
	case *StmtBlockNode:
		return w.ActStmtBlock(n.(*StmtBlockNode))
	case *StmtList:
		return w.ActStmtList(n.(*StmtList))
	case *StmtNode:
		return w.ActStmt(n.(*StmtNode))
	case *IfStmtNode:
		return w.ActIfStmt(n.(*IfStmtNode))
	case *IfNode:
		return w.ActIf(n.(*IfNode))
	case *ElseNode:
		return w.ActElse(n.(*ElseNode))
	case *ElseIfList:
		return w.ActElseIfList(n.(*ElseIfList))
	case *ElseIfNode:
		return w.ActElseIf(n.(*ElseIfNode))
	case *WhileNode:
		return w.ActWhile(n.(*WhileNode))
	case *DoWhileNode:
		return w.ActDoWhile(n.(*DoWhileNode))
	case *ContinueStmtNode:
		return w.ActContinueStmt(n.(*ContinueStmtNode))
	case *BreakStmtNode:
		return w.ActBreakStmt(n.(*BreakStmtNode))
	case *ReturnStmtNode:
		return w.ActReturnStmt(n.(*ReturnStmtNode))
	case *RequireStmtNode:
		return w.ActRequireStmt(n.(*RequireStmtNode))
	case *ThrowStmtNode:
		return w.ActThrowStmt(n.(*ThrowStmtNode))
	case *EmitStmtNode:
		return w.ActEmitStmt(n.(*EmitStmtNode))
	case *GotoStmtNode:
		return w.ActGotoStmt(n.(*GotoStmtNode))
	case *CalcAssignStmtNode:
		return w.ActCalcAssignStmt(n.(*CalcAssignStmtNode))
	case *ExprStmtNode:
		return w.ActExprStmt(n.(*ExprStmtNode))
	case *CastExpressionNode:
		return w.ActCastExpression(n.(*CastExpressionNode))
	case *ExternalCallExprNode:
		return w.ActExternalCallExpr(n.(*ExternalCallExprNode))
	case *ExtSpecifierList:
		return w.ActExtSpecifierList(n.(*ExtSpecifierList))
	case *ExtSpecifierNode:
		return w.ActExtSpecifier(n.(*ExtSpecifierNode))
	case *ExpressionList:
		return w.ActExpressionList(n.(*ExpressionList))
	case *ExpressionNode:
		return w.ActExpression(n.(*ExpressionNode))
	case *SubexprNode:
		return w.ActSubexpr(n.(*SubexprNode))
	case *RvalueNode:
		return w.ActRvalue(n.(*RvalueNode))
	case *LvalueNode:
		return w.ActLvalue(n.(*LvalueNode))
	case *AllocSizeNode:
		return w.ActAllocSize(n.(*AllocSizeNode))
	case *PrimaryList:
		return w.ActPrimaryList(n.(*PrimaryList))
	case *PrimaryNode:
		return w.ActPrimary(n.(*PrimaryNode))
	case *TokenNode:
		return w.ActToken(n.(*TokenNode))
	case *FallbackStmtNode:
		return w.ActFallbackStmt(n.(*FallbackStmtNode))
	default:
		return
	}
}
