// Code generated by goyacc -p Item -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package parser

import __yyfmt__ "fmt"

//line parser.go.y:2
import . "github.com/ethereum/go-ethereum/substrate_parser/ast"

//line parser.go.y:38
type ItemSymType struct {
	yys  int
	typ  int
	val  string
	pos  position
	node AstNode
	list AstNode
}

const COMMENT = 57346
const MESSAGE = 57347
const GOTOADDRESS = 57348
const BOOLLITERAL = 57349
const NUM = 57350
const HEX = 57351
const ID = 57352
const MAPPING = 57353
const STORAGET = 57354
const BOOL = 57355
const UINT = 57356
const INT = 57357
const BYTE = 57358
const ADDRESS = 57359
const STRING = 57360
const ARRAY = 57361
const STRUCT = 57362
const FUNCTION = 57363
const MEM = 57364
const STORAGE = 57365
const IF = 57366
const ELSEIF = 57367
const ELSE = 57368
const WHILE = 57369
const DO = 57370
const BREAK = 57371
const CONTINUE = 57372
const RETURN = 57373
const THIS = 57374
const NEW = 57375
const EMIT = 57376
const THROW = 57377
const REQUIRE = 57378
const GOTO = 57379
const PUBLIC = 57380
const PRIVATE = 57381
const PAYABLE = 57382
const NONPAYABLE = 57383
const MSGGAS = 57384
const MSGVAL = 57385
const MSGDATA = 57386
const MSGSENDER = 57387
const ADD = 57388
const SUB = 57389
const NEG = 57390
const NOT = 57391
const EXP = 57392
const MUL = 57393
const DIV = 57394
const MOD = 57395
const SL = 57396
const SR = 57397
const AND = 57398
const XOR = 57399
const OR = 57400
const LT = 57401
const GT = 57402
const LE = 57403
const GE = 57404
const EQ = 57405
const NEQ = 57406
const LOGICALAND = 57407
const LOGICALOR = 57408
const ASSIGN = 57409
const ASSIGNADD = 57410
const ASSIGNSUB = 57411
const ASSIGNMUL = 57412
const ASSIGNDIV = 57413
const ARROW = 57414

var ItemToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"COMMENT",
	"MESSAGE",
	"GOTOADDRESS",
	"BOOLLITERAL",
	"NUM",
	"HEX",
	"ID",
	"MAPPING",
	"STORAGET",
	"BOOL",
	"UINT",
	"INT",
	"BYTE",
	"ADDRESS",
	"STRING",
	"ARRAY",
	"STRUCT",
	"FUNCTION",
	"MEM",
	"STORAGE",
	"IF",
	"ELSEIF",
	"ELSE",
	"WHILE",
	"DO",
	"BREAK",
	"CONTINUE",
	"RETURN",
	"THIS",
	"NEW",
	"EMIT",
	"THROW",
	"REQUIRE",
	"GOTO",
	"PUBLIC",
	"PRIVATE",
	"PAYABLE",
	"NONPAYABLE",
	"MSGGAS",
	"MSGVAL",
	"MSGDATA",
	"MSGSENDER",
	"ADD",
	"SUB",
	"NEG",
	"NOT",
	"EXP",
	"MUL",
	"DIV",
	"MOD",
	"SL",
	"SR",
	"AND",
	"XOR",
	"OR",
	"LT",
	"GT",
	"LE",
	"GE",
	"EQ",
	"NEQ",
	"LOGICALAND",
	"LOGICALOR",
	"ASSIGN",
	"ASSIGNADD",
	"ASSIGNSUB",
	"ASSIGNMUL",
	"ASSIGNDIV",
	"ARROW",
	"';'",
	"'('",
	"')'",
	"'{'",
	"'}'",
	"','",
	"'['",
	"']'",
	"'.'",
	"'*'",
	"':'",
	"'?'",
}

var ItemStatenames = [...]string{}

const ItemEofCode = 1
const ItemErrCode = 2
const ItemInitialStackSize = 16

//line parser.go.y:629

type Token struct {
	val string
	pos position
}

func setPos(p position) Pos {
	return NewPos(p.line, p.column)
}

//line yacctab:1
var ItemExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 30,
	9, 1,
	10, 1,
	74, 1,
	-2, 58,
	-1, 81,
	75, 73,
	78, 73,
	-2, 194,
	-1, 166,
	12, 192,
	74, 192,
	79, 192,
	81, 192,
	-2, 182,
	-1, 184,
	75, 50,
	78, 50,
	-2, 207,
	-1, 191,
	75, 72,
	78, 72,
	-2, 194,
	-1, 192,
	74, 123,
	-2, 189,
	-1, 195,
	67, 152,
	78, 152,
	-2, 154,
}

const ItemPrivate = 57344

const ItemLast = 1022

var ItemAct = [...]int{
	66, 280, 235, 84, 181, 301, 281, 231, 127, 114,
	10, 59, 10, 83, 17, 85, 17, 185, 168, 120,
	177, 61, 94, 93, 95, 17, 91, 92, 125, 75,
	90, 64, 12, 88, 12, 52, 52, 101, 9, 173,
	87, 89, 57, 169, 56, 8, 216, 42, 80, 81,
	55, 82, 104, 106, 217, 86, 73, 225, 111, 5,
	224, 61, 46, 49, 54, 17, 60, 113, 105, 115,
	219, 58, 308, 60, 272, 81, 52, 52, 58, 17,
	52, 60, 60, 113, 116, 56, 58, 58, 56, 338,
	339, 55, 126, 56, 55, 75, 351, 214, 179, 73,
	215, 132, 73, 73, 108, 109, 137, 341, 110, 172,
	60, 333, 174, 14, 113, 58, 17, 136, 76, 135,
	340, 131, 337, 74, 132, 77, 178, 305, 304, 182,
	17, 303, 336, 183, 335, 162, 163, 164, 165, 52,
	332, 330, 191, 329, 328, 194, 17, 56, 56, 56,
	166, 71, 70, 55, 189, 291, 292, 293, 294, 175,
	133, 76, 67, 123, 76, 76, 74, 170, 134, 74,
	74, 134, 77, 197, 202, 200, 203, 201, 199, 196,
	213, 204, 208, 209, 198, 205, 178, 206, 218, 195,
	17, 193, 130, 67, 65, 75, 190, 210, 302, 315,
	220, 307, 299, 22, 17, 19, 20, 21, 28, 56,
	212, 135, 226, 227, 298, 286, 72, 275, 67, 138,
	229, 274, 119, 78, 147, 182, 79, 148, 253, 183,
	27, 273, 149, 252, 228, 17, 140, 141, 278, 253,
	25, 23, 24, 26, 252, 161, 276, 143, 144, 145,
	146, 288, 289, 317, 295, 151, 152, 287, 253, 53,
	306, 300, 188, 252, 75, 157, 158, 159, 154, 155,
	126, 171, 60, 207, 80, 81, 7, 58, 192, 311,
	50, 312, 29, 297, 310, 314, 313, 186, 187, 128,
	126, 118, 117, 121, 122, 316, 285, 284, 320, 318,
	129, 323, 324, 309, 259, 80, 81, 223, 326, 305,
	304, 129, 126, 303, 126, 126, 327, 6, 69, 334,
	47, 50, 222, 96, 331, 319, 4, 321, 322, 45,
	48, 3, 103, 167, 44, 160, 344, 345, 346, 347,
	342, 253, 343, 349, 350, 348, 252, 156, 153, 150,
	246, 22, 352, 19, 20, 21, 28, 43, 142, 37,
	31, 32, 33, 34, 35, 36, 18, 63, 40, 41,
	271, 107, 139, 261, 262, 264, 263, 266, 27, 102,
	269, 268, 267, 270, 290, 325, 247, 279, 25, 23,
	24, 26, 97, 98, 100, 99, 245, 244, 243, 242,
	241, 240, 239, 238, 62, 11, 237, 11, 51, 37,
	31, 32, 33, 34, 35, 36, 236, 63, 234, 233,
	265, 232, 219, 277, 230, 68, 16, 15, 246, 22,
	29, 19, 20, 21, 28, 43, 180, 37, 31, 32,
	33, 34, 35, 36, 18, 63, 40, 41, 271, 51,
	176, 261, 262, 264, 263, 266, 27, 102, 269, 268,
	267, 270, 2, 258, 257, 256, 25, 23, 24, 26,
	97, 98, 100, 99, 22, 255, 19, 20, 21, 28,
	43, 254, 37, 31, 32, 33, 34, 35, 36, 18,
	63, 40, 41, 251, 250, 249, 248, 283, 265, 282,
	219, 27, 102, 260, 13, 38, 1, 0, 29, 0,
	0, 25, 23, 24, 26, 97, 98, 100, 99, 22,
	0, 19, 20, 21, 28, 43, 0, 37, 31, 32,
	33, 34, 35, 36, 18, 63, 40, 41, 0, 0,
	0, 0, 0, 39, 123, 0, 27, 102, 0, 0,
	0, 0, 0, 29, 0, 0, 25, 23, 24, 26,
	97, 98, 100, 99, 22, 0, 19, 20, 21, 28,
	43, 0, 37, 31, 32, 33, 34, 35, 36, 18,
	63, 40, 41, 0, 0, 0, 0, 0, 39, 0,
	0, 27, 102, 0, 124, 0, 0, 0, 29, 0,
	0, 25, 23, 24, 26, 97, 98, 100, 99, 22,
	0, 19, 20, 21, 28, 43, 0, 37, 31, 32,
	33, 34, 35, 36, 18, 63, 40, 41, 0, 0,
	0, 0, 0, 39, 0, 0, 27, 102, 0, 112,
	0, 0, 0, 29, 0, 0, 25, 23, 24, 26,
	97, 98, 100, 99, 22, 0, 19, 20, 21, 28,
	43, 0, 37, 31, 32, 33, 34, 35, 36, 18,
	63, 40, 41, 0, 0, 0, 0, 0, 39, 0,
	0, 27, 102, 0, 0, 0, 0, 0, 29, 0,
	0, 25, 23, 24, 26, 97, 98, 100, 99, 22,
	0, 19, 20, 21, 28, 43, 0, 37, 31, 32,
	33, 34, 35, 36, 18, 63, 40, 41, 0, 0,
	0, 0, 0, 296, 0, 0, 27, 0, 0, 0,
	0, 0, 0, 29, 0, 0, 25, 23, 24, 26,
	0, 0, 22, 0, 19, 20, 21, 28, 43, 0,
	37, 31, 32, 33, 34, 35, 36, 18, 63, 40,
	41, 0, 0, 0, 0, 0, 0, 0, 39, 27,
	0, 0, 0, 221, 0, 0, 0, 0, 29, 25,
	23, 24, 26, 0, 0, 22, 0, 19, 20, 21,
	28, 43, 0, 37, 31, 32, 33, 34, 35, 36,
	18, 63, 40, 41, 0, 0, 0, 0, 0, 0,
	0, 39, 27, 102, 211, 0, 0, 0, 0, 0,
	0, 29, 25, 23, 24, 26, 0, 0, 22, 0,
	19, 20, 21, 28, 43, 0, 37, 31, 32, 33,
	34, 35, 36, 18, 63, 40, 41, 0, 0, 0,
	0, 0, 0, 0, 39, 27, 0, 0, 0, 0,
	0, 0, 0, 0, 29, 25, 23, 24, 26, 0,
	0, 22, 0, 19, 20, 21, 184, 43, 0, 37,
	31, 32, 33, 34, 35, 36, 18, 63, 40, 41,
	0, 0, 0, 0, 0, 0, 0, 39, 27, 0,
	0, 0, 0, 0, 0, 0, 0, 29, 25, 23,
	24, 26, 0, 0, 22, 0, 19, 20, 21, 28,
	43, 0, 37, 31, 32, 33, 34, 35, 36, 18,
	30, 40, 41, 22, 0, 19, 20, 21, 28, 0,
	39, 27, 22, 0, 19, 20, 21, 28, 18, 53,
	29, 25, 23, 24, 26, 0, 0, 0, 53, 0,
	27, 0, 0, 0, 0, 0, 0, 0, 0, 27,
	25, 23, 24, 26, 0, 0, 0, 0, 0, 25,
	23, 24, 26, 39, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 29, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 29, 0, 0, 0, 0, 0, 0, 0,
	0, 29,
}

var ItemPact = [...]int{
	909, -1000, 909, 928, 937, 238, -1000, -1000, -1000, -1000,
	198, 823, 120, 142, -1000, -1000, -1000, 91, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 149, 604,
	-11, -11, -1000, -1000, 928, 937, 238, -1000, 937, 238,
	-1000, 823, 120, -1000, 238, -1000, -1000, 89, 559, -1000,
	604, 8, -1000, -1000, -1000, 823, -1000, 287, 148, 255,
	-1000, -1000, 88, -1000, 514, -1000, 604, 279, 396, 46,
	85, 7, -1000, 90, 53, 39, 154, 173, 188, 166,
	170, 176, 201, 222, 214, -1000, 195, 780, 780, 780,
	780, -1000, 823, -38, -1000, 604, -1000, 937, 238, 238,
	238, -1000, 259, 29, 7, 84, 823, 23, -1000, 866,
	247, -1000, -1000, -1000, 250, 79, 39, -1000, -1000, -1000,
	124, -1000, 823, -1000, 268, 604, 604, 604, 604, 604,
	-1000, -1000, 604, -1000, -1000, -1000, -1000, 604, 604, 604,
	604, -1000, -1000, 604, -1000, -1000, 604, -1000, -1000, -1000,
	604, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -38, 263,
	238, -1000, -1000, 604, 604, -1000, 737, -1000, 198, 89,
	22, -1000, 36, 44, -1000, -6, -1000, -1000, -1000, -1000,
	694, 7, -1000, 154, -1000, -1000, 173, 188, 166, 170,
	176, 201, 222, 214, -1000, -1000, -1000, -1000, -20, -23,
	-1000, 89, 89, -1000, 255, 866, -1000, -1000, -1000, 424,
	-1, 823, 147, 143, -1000, -1000, -1000, -1000, 247, -1000,
	346, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 271, 141, 424,
	89, 89, 87, 89, 649, 140, 128, 604, 122, 89,
	127, -1000, -1000, -1000, -1000, 469, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -8, 604, 604, -6, -1000, -1000, 271,
	-1000, -1000, -6, 125, -1000, -1000, 604, 226, -1000, -1000,
	604, -1000, -1000, -1000, -1000, -1000, 604, 89, 604, 604,
	145, 89, 304, -1000, -1000, -1000, -1000, 604, 69, 68,
	66, -1000, -1000, -1000, -1000, 604, 65, 37, 89, 59,
	-1000, 57, 47, -1000, -1000, 12, -1000, 45, -1000, -1000,
	-1000, 32, 424, 604, -1000, 89, 89, 89, 89, 304,
	-6, -6, -1000, 21, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 89, -1000,
}

var ItemPgo = [...]int{
	0, 506, 0, 304, 505, 504, 503, 499, 497, 496,
	495, 494, 493, 481, 475, 465, 464, 463, 462, 450,
	331, 326, 59, 317, 20, 276, 45, 38, 436, 4,
	226, 9, 113, 404, 427, 426, 31, 425, 19, 17,
	424, 2, 7, 421, 419, 418, 416, 406, 403, 402,
	401, 400, 399, 398, 397, 396, 387, 386, 6, 1,
	385, 5, 28, 15, 384, 372, 358, 349, 348, 347,
	335, 333, 47, 332, 18, 8, 51, 3, 55, 40,
	33, 41, 30, 26, 27, 23, 22, 24, 323, 37,
	13, 11, 322, 307,
}

var ItemR1 = [...]int{
	0, 5, 4, 6, 7, 8, 9, 10, 11, 12,
	13, 14, 15, 16, 17, 2, 2, 3, 1, 1,
	1, 1, 1, 1, 1, 1, 18, 18, 23, 19,
	19, 24, 20, 20, 25, 21, 21, 26, 26, 22,
	22, 27, 27, 37, 37, 28, 28, 28, 29, 29,
	29, 32, 32, 32, 32, 32, 32, 32, 32, 33,
	34, 34, 35, 31, 31, 31, 31, 31, 31, 31,
	31, 31, 30, 30, 30, 41, 40, 40, 40, 42,
	42, 42, 42, 42, 42, 42, 42, 42, 42, 42,
	42, 42, 42, 42, 43, 43, 43, 43, 57, 59,
	56, 56, 58, 44, 45, 46, 47, 50, 50, 51,
	52, 53, 54, 54, 60, 60, 61, 61, 61, 48,
	49, 55, 72, 92, 73, 71, 71, 71, 93, 74,
	62, 62, 63, 63, 64, 64, 64, 64, 65, 65,
	66, 66, 66, 66, 67, 67, 68, 68, 69, 69,
	69, 70, 75, 76, 76, 77, 77, 78, 78, 79,
	79, 80, 80, 81, 81, 82, 82, 83, 83, 84,
	84, 85, 85, 86, 86, 87, 87, 88, 88, 88,
	88, 88, 89, 89, 89, 90, 90, 90, 90, 90,
	90, 90, 90, 90, 90, 91, 91, 91, 36, 36,
	36, 36, 36, 36, 36, 36, 36, 36, 36, 38,
	38, 39, 39, 39,
}

var ItemR2 = [...]int{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 2, 1, 2, 4, 3,
	3, 3, 2, 2, 2, 1, 2, 1, 3, 2,
	1, 3, 2, 1, 6, 2, 1, 5, 2, 2,
	1, 8, 5, 1, 1, 3, 1, 0, 2, 2,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	6, 8, 3, 1, 1, 1, 1, 3, 4, 2,
	2, 4, 3, 1, 0, 3, 2, 1, 0, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 3, 2, 2, 1, 5, 2,
	2, 1, 5, 5, 7, 2, 2, 5, 3, 5,
	5, 3, 3, 5, 3, 1, 1, 1, 1, 4,
	2, 2, 4, 0, 7, 2, 1, 0, 0, 6,
	1, 0, 3, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 3, 1, 3, 1, 3, 1,
	3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
	3, 1, 3, 1, 3, 1, 3, 2, 2, 2,
	2, 1, 2, 2, 1, 2, 2, 2, 4, 3,
	3, 1, 1, 3, 1, 3, 5, 5, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 0,
}

var ItemChk = [...]int{
	-1000, -1, -18, -20, -21, -22, -23, -25, -26, -27,
	-31, -33, -36, -5, -32, -34, -35, -90, 20, 7,
	8, 9, 5, 43, 44, 42, 45, 32, 10, 84,
	21, 14, 15, 16, 17, 18, 19, 13, -4, 74,
	22, 23, -72, 11, -20, -21, -22, -23, -21, -22,
	-25, -33, -36, 21, -22, -26, -27, -36, 79, -91,
	74, -31, -33, 21, -36, 74, -2, 73, -37, -3,
	10, 9, 74, 12, 79, -91, 74, 81, 74, -30,
	-75, -31, -76, -90, -77, -63, -78, -79, -80, -81,
	-82, -83, -84, -85, -86, -87, -88, 46, 47, 49,
	48, -89, 33, -73, -91, 79, -91, -21, -22, -22,
	-22, -2, 80, -75, -31, -75, 76, -30, 4, 74,
	-38, 38, 39, 75, 80, -62, -63, -75, 10, 32,
	-32, 75, 78, 75, 81, 66, 78, 67, 65, -65,
	63, 64, -66, 59, 60, 61, 62, 58, 57, 56,
	-67, 54, 55, -68, 46, 47, -69, 51, 52, 53,
	-70, 50, -89, -89, -89, -89, -72, -71, -74, 81,
	-22, 12, 80, 10, 83, 75, -19, -24, -31, 75,
	-28, -29, -31, -90, 10, -39, 40, 41, 12, 75,
	72, -31, 10, -78, -75, -76, -79, -80, -81, -82,
	-83, -84, -85, -86, -87, -87, -74, 10, -75, -75,
	-24, 77, -36, -2, 75, 78, 10, 10, -41, 76,
	-31, 79, -92, -93, 80, 80, -2, -2, -38, -29,
	-40, -42, -43, -44, -45, -41, -46, -47, -48, -49,
	-50, -51, -52, -53, -54, -55, 4, -57, -9, -10,
	-11, -12, -90, -75, -13, -14, -15, -16, -17, -3,
	-6, 27, 28, 30, 29, 74, 31, 36, 35, 34,
	37, 24, 75, -31, 74, 74, -39, 77, -42, -56,
	-59, -58, -7, -8, 26, 25, 74, -42, -2, -2,
	-64, 68, 69, 70, 71, -2, 74, -62, 74, 74,
	-77, -61, 76, 9, 6, 5, -2, 74, 80, -62,
	-75, -41, -59, -58, -41, 74, -75, 27, -75, -62,
	-2, -62, -62, -2, -2, -60, -61, -75, 75, 75,
	75, -75, 75, 74, -2, 75, 75, 75, 77, 78,
	75, 75, -42, -75, -2, -2, -2, -2, -61, -41,
	-41, 75, -2,
}

var ItemDef = [...]int{
	0, -2, 0, 0, 0, 25, 27, 33, 36, 40,
	194, 65, 191, 0, 63, 64, 66, 0, 59, 198,
	199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
	-2, 51, 52, 53, 54, 55, 56, 57, 0, 74,
	0, 0, 192, 2, 0, 0, 22, 26, 0, 23,
	32, 0, 0, 1, 24, 35, 39, 0, 0, 69,
	0, 194, 65, 58, 191, 74, 38, 16, 0, 0,
	43, 44, 0, 70, 0, 187, 131, 0, 0, 0,
	133, -2, 152, 184, 153, 0, 155, 157, 159, 161,
	163, 165, 167, 169, 171, 173, 175, 0, 0, 0,
	0, 181, 0, 127, 185, 0, 186, 0, 19, 20,
	21, 28, 67, 133, 194, 133, 0, 0, 15, 47,
	213, 209, 210, 17, 0, 0, 130, 133, 189, 190,
	0, 62, 0, 193, 0, 0, 0, 0, 0, 0,
	138, 139, 0, 140, 141, 142, 143, 0, 0, 0,
	0, 144, 145, 0, 146, 147, 0, 148, 149, 150,
	0, 151, 177, 178, 179, 180, -2, 183, 126, 0,
	18, 68, 195, 0, 0, 122, 0, 30, 194, 0,
	0, 46, 194, 0, -2, 0, 211, 212, 71, 188,
	0, -2, -2, 156, 132, -2, 158, 160, 162, 164,
	166, 168, 170, 172, 174, 176, 125, 128, 133, 133,
	29, 0, 0, 37, 0, 0, 48, 49, 42, 78,
	194, 0, 0, 0, 196, 197, 34, 31, 213, 45,
	0, 77, 79, 80, 81, 82, 83, 84, 85, 86,
	87, 88, 89, 90, 91, 92, 93, 97, 0, 0,
	0, 0, 184, 133, 131, 0, 0, 0, 0, 0,
	0, 6, 7, 8, 9, 74, 10, 11, 12, 13,
	14, 3, 60, 194, 131, 0, 0, 75, 76, 95,
	96, 101, 0, 0, 4, 5, 0, 0, 105, 106,
	0, 134, 135, 136, 137, 120, 74, 0, 131, 131,
	0, 0, 0, 116, 117, 118, 121, 0, 0, 0,
	133, 41, 94, 100, 99, 0, 133, 0, 133, 0,
	108, 0, 0, 111, 112, 0, 115, 133, 61, 124,
	129, 133, 0, 0, 119, 0, 0, 0, 0, 0,
	0, 0, 103, 133, 107, 109, 110, 113, 114, 98,
	102, 0, 104,
}

var ItemTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	74, 75, 82, 3, 78, 3, 81, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 83, 73,
	3, 3, 3, 84, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 79, 3, 80, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 76, 3, 77,
}

var ItemTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72,
}

var ItemTok3 = [...]int{
	0,
}

var ItemErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	ItemDebug        = 0
	ItemErrorVerbose = false
)

type ItemLexer interface {
	Lex(lval *ItemSymType) int
	Error(s string)
}

type ItemParser interface {
	Parse(ItemLexer) int
	Lookahead() int
}

type ItemParserImpl struct {
	lval  ItemSymType
	stack [ItemInitialStackSize]ItemSymType
	char  int
}

func (p *ItemParserImpl) Lookahead() int {
	return p.char
}

func ItemNewParser() ItemParser {
	return &ItemParserImpl{}
}

const ItemFlag = -1000

func ItemTokname(c int) string {
	if c >= 1 && c-1 < len(ItemToknames) {
		if ItemToknames[c-1] != "" {
			return ItemToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func ItemStatname(s int) string {
	if s >= 0 && s < len(ItemStatenames) {
		if ItemStatenames[s] != "" {
			return ItemStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func ItemErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !ItemErrorVerbose {
		return "syntax error"
	}

	for _, e := range ItemErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + ItemTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := ItemPact[state]
	for tok := TOKSTART; tok-1 < len(ItemToknames); tok++ {
		if n := base + tok; n >= 0 && n < ItemLast && ItemChk[ItemAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if ItemDef[state] == -2 {
		i := 0
		for ItemExca[i] != -1 || ItemExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; ItemExca[i] >= 0; i += 2 {
			tok := ItemExca[i]
			if tok < TOKSTART || ItemExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if ItemExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += ItemTokname(tok)
	}
	return res
}

func Itemlex1(lex ItemLexer, lval *ItemSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = ItemTok1[0]
		goto out
	}
	if char < len(ItemTok1) {
		token = ItemTok1[char]
		goto out
	}
	if char >= ItemPrivate {
		if char < ItemPrivate+len(ItemTok2) {
			token = ItemTok2[char-ItemPrivate]
			goto out
		}
	}
	for i := 0; i < len(ItemTok3); i += 2 {
		token = ItemTok3[i+0]
		if token == char {
			token = ItemTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = ItemTok2[1] /* unknown char */
	}
	if ItemDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", ItemTokname(token), uint(char))
	}
	return char, token
}

func ItemParse(Itemlex ItemLexer) int {
	return ItemNewParser().Parse(Itemlex)
}

func (Itemrcvr *ItemParserImpl) Parse(Itemlex ItemLexer) int {
	var Itemn int
	var ItemVAL ItemSymType
	var ItemDollar []ItemSymType
	_ = ItemDollar // silence set and not used
	ItemS := Itemrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Itemstate := 0
	Itemrcvr.char = -1
	Itemtoken := -1 // Itemrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Itemstate = -1
		Itemrcvr.char = -1
		Itemtoken = -1
	}()
	Itemp := -1
	goto Itemstack

ret0:
	return 0

ret1:
	return 1

Itemstack:
	/* put a state and value onto the stack */
	if ItemDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", ItemTokname(Itemtoken), ItemStatname(Itemstate))
	}

	Itemp++
	if Itemp >= len(ItemS) {
		nyys := make([]ItemSymType, len(ItemS)*2)
		copy(nyys, ItemS)
		ItemS = nyys
	}
	ItemS[Itemp] = ItemVAL
	ItemS[Itemp].yys = Itemstate

Itemnewstate:
	Itemn = ItemPact[Itemstate]
	if Itemn <= ItemFlag {
		goto Itemdefault /* simple state */
	}
	if Itemrcvr.char < 0 {
		Itemrcvr.char, Itemtoken = Itemlex1(Itemlex, &Itemrcvr.lval)
	}
	Itemn += Itemtoken
	if Itemn < 0 || Itemn >= ItemLast {
		goto Itemdefault
	}
	Itemn = ItemAct[Itemn]
	if ItemChk[Itemn] == Itemtoken { /* valid shift */
		Itemrcvr.char = -1
		Itemtoken = -1
		ItemVAL = Itemrcvr.lval
		Itemstate = Itemn
		if Errflag > 0 {
			Errflag--
		}
		goto Itemstack
	}

Itemdefault:
	/* default state action */
	Itemn = ItemDef[Itemstate]
	if Itemn == -2 {
		if Itemrcvr.char < 0 {
			Itemrcvr.char, Itemtoken = Itemlex1(Itemlex, &Itemrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if ItemExca[xi+0] == -1 && ItemExca[xi+1] == Itemstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Itemn = ItemExca[xi+0]
			if Itemn < 0 || Itemn == Itemtoken {
				break
			}
		}
		Itemn = ItemExca[xi+1]
		if Itemn < 0 {
			goto ret0
		}
	}
	if Itemn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Itemlex.Error(ItemErrorMessage(Itemstate, Itemtoken))
			Nerrs++
			if ItemDebug >= 1 {
				__yyfmt__.Printf("%s", ItemStatname(Itemstate))
				__yyfmt__.Printf(" saw %s\n", ItemTokname(Itemtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Itemp >= 0 {
				Itemn = ItemPact[ItemS[Itemp].yys] + ItemErrCode
				if Itemn >= 0 && Itemn < ItemLast {
					Itemstate = ItemAct[Itemn] /* simulate a shift of "error" */
					if ItemChk[Itemstate] == ItemErrCode {
						goto Itemstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if ItemDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", ItemS[Itemp].yys)
				}
				Itemp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if ItemDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", ItemTokname(Itemtoken))
			}
			if Itemtoken == ItemEofCode {
				goto ret1
			}
			Itemrcvr.char = -1
			Itemtoken = -1
			goto Itemnewstate /* try again in the same state */
		}
	}

	/* reduction by production Itemn */
	if ItemDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Itemn, ItemStatname(Itemstate))
	}

	Itemnt := Itemn
	Itempt := Itemp
	_ = Itempt // guard against "declared and not used"

	Itemp -= ItemR2[Itemn]
	// Itemp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Itemp+1 >= len(ItemS) {
		nyys := make([]ItemSymType, len(ItemS)*2)
		copy(nyys, ItemS)
		ItemS = nyys
	}
	ItemVAL = ItemS[Itemp+1]

	/* consult goto table to find next state */
	Itemn = ItemR1[Itemn]
	Itemg := ItemPgo[Itemn]
	Itemj := Itemg + ItemS[Itemp].yys + 1

	if Itemj >= ItemLast {
		Itemstate = ItemAct[Itemg]
	} else {
		Itemstate = ItemAct[Itemj]
		if ItemChk[Itemstate] != -Itemn {
			Itemstate = ItemAct[Itemg]
		}
	}
	// dummy call; replaced with literal code
	switch Itemnt {

	case 1:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:75
		{
			ItemVAL.pos = buffer.pos
		}
	case 2:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:76
		{
			ItemVAL.pos = buffer.pos
		}
	case 3:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:77
		{
			ItemVAL.pos = buffer.pos
		}
	case 4:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:78
		{
			ItemVAL.pos = buffer.pos
		}
	case 5:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:79
		{
			ItemVAL.pos = buffer.pos
		}
	case 6:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:80
		{
			ItemVAL.pos = buffer.pos
		}
	case 7:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:81
		{
			ItemVAL.pos = buffer.pos
		}
	case 8:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:82
		{
			ItemVAL.pos = buffer.pos
		}
	case 9:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:83
		{
			ItemVAL.pos = buffer.pos
		}
	case 10:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:84
		{
			ItemVAL.pos = buffer.pos
		}
	case 11:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:85
		{
			ItemVAL.pos = buffer.pos
		}
	case 12:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:86
		{
			ItemVAL.pos = buffer.pos
		}
	case 13:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:87
		{
			ItemVAL.pos = buffer.pos
		}
	case 14:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:88
		{
			ItemVAL.pos = buffer.pos
		}
	case 15:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:91
		{
			ItemVAL.val = buffer.val
		}
	case 16:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:94
		{
			ItemVAL.val = ""
		}
	case 17:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:98
		{
			ItemVAL.pos = buffer.pos
		}
	case 18:
		ItemDollar = ItemS[Itempt-4 : Itempt+1]
//line parser.go.y:101
		{
			Itemlex.(*Lexer).Root = BuildAST(ItemDollar[1].list.(*StorageDeclList), ItemDollar[2].list.(*StructDefList), ItemDollar[3].list.(*EventDeclList), ItemDollar[4].list.(*FunctionDefList))
		}
	case 19:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:104
		{
			Itemlex.(*Lexer).Root = BuildAST(ItemDollar[1].list.(*StorageDeclList), ItemDollar[2].list.(*StructDefList), nil, ItemDollar[3].list.(*FunctionDefList))
		}
	case 20:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:107
		{
			Itemlex.(*Lexer).Root = BuildAST(ItemDollar[1].list.(*StorageDeclList), nil, ItemDollar[2].list.(*EventDeclList), ItemDollar[3].list.(*FunctionDefList))
		}
	case 21:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:110
		{
			Itemlex.(*Lexer).Root = BuildAST(nil, ItemDollar[1].list.(*StructDefList), ItemDollar[2].list.(*EventDeclList), ItemDollar[3].list.(*FunctionDefList))
		}
	case 22:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:113
		{
			Itemlex.(*Lexer).Root = BuildAST(ItemDollar[1].list.(*StorageDeclList), nil, nil, ItemDollar[2].list.(*FunctionDefList))
		}
	case 23:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:116
		{
			Itemlex.(*Lexer).Root = BuildAST(nil, ItemDollar[1].list.(*StructDefList), nil, ItemDollar[2].list.(*FunctionDefList))
		}
	case 24:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:119
		{
			Itemlex.(*Lexer).Root = BuildAST(nil, nil, ItemDollar[1].list.(*EventDeclList), ItemDollar[2].list.(*FunctionDefList))
		}
	case 25:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:122
		{
			Itemlex.(*Lexer).Root = BuildAST(nil, nil, nil, ItemDollar[1].list.(*FunctionDefList))
		}
	case 26:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:127
		{
			ItemVAL.list = NewStorageDeclList(ItemDollar[1].list.(*StorageDeclList), ItemDollar[2].node.(*StorageDeclNode))
		}
	case 27:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:130
		{
			ItemVAL.list = NewStorageDeclList(nil, ItemDollar[1].node.(*StorageDeclNode))
		}
	case 28:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:134
		{
			ItemVAL.node = NewStorageDeclNode(ItemDollar[1].node.(*TypeNameNode), ItemDollar[2].node.(*PrimaryNode), ItemDollar[3].val)
		}
	case 29:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:139
		{
			ItemVAL.list = NewStructFieldList(ItemDollar[1].list.(*StructFieldList), ItemDollar[2].node.(*StructFieldNode))
		}
	case 30:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:142
		{
			ItemVAL.list = NewStructFieldList(nil, ItemDollar[1].node.(*StructFieldNode))
		}
	case 31:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:146
		{
			ItemVAL.node = NewStructFieldNode(ItemDollar[1].node.(*TypeNameNode), ItemDollar[2].node.(*PrimaryNode))
		}
	case 32:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:151
		{
			ItemVAL.list = NewStructDefList(ItemDollar[1].list.(*StructDefList), ItemDollar[2].node.(*StructDefNode))
		}
	case 33:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:154
		{
			ItemVAL.list = NewStructDefList(nil, ItemDollar[1].node.(*StructDefNode))
		}
	case 34:
		ItemDollar = ItemS[Itempt-6 : Itempt+1]
//line parser.go.y:158
		{
			ItemVAL.node = NewStructDefNode(ItemDollar[2].node.(*TypeNameNode), ItemDollar[4].list.(*StructFieldList))
		}
	case 35:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:164
		{
			ItemVAL.list = NewEventDeclList(ItemDollar[1].list.(*EventDeclList), ItemDollar[2].node.(*EventDeclNode))
		}
	case 36:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:167
		{
			ItemVAL.list = NewEventDeclList(nil, ItemDollar[1].node.(*EventDeclNode))
		}
	case 37:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:171
		{
			t := ItemDollar[1].node.(*PrimaryNode).Typ //primary must be ID
			if t != TypeID {
				Itemlex.Error("Primary is not ID in EventDecl")
				return 1
			}
			ItemVAL.node = NewEventDeclNode(ItemDollar[1].node.(*PrimaryNode), ItemDollar[3].list.(*TypeNameList))
		}
	case 38:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:179
		{
			t := ItemDollar[1].node.(*PrimaryNode).Typ //primary must be HEX
			if t != TypeHEX {
				Itemlex.Error("Primary is not HEX in EventDecl")
				return 1
			}
			ItemVAL.node = NewEventDeclNode(ItemDollar[1].node.(*PrimaryNode), nil)
		}
	case 39:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:189
		{
			ItemVAL.list = NewFunctionDefList(ItemDollar[1].list.(*FunctionDefList), ItemDollar[2].node.(*FunctionDefNode))
		}
	case 40:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:192
		{
			ItemVAL.list = NewFunctionDefList(nil, ItemDollar[1].node.(*FunctionDefNode))
		}
	case 41:
		ItemDollar = ItemS[Itempt-8 : Itempt+1]
//line parser.go.y:196
		{
			ItemVAL.node = NewFunctionDefNode(setPos(ItemDollar[1].pos), ItemDollar[2].node.(*PrimaryNode), ItemDollar[4].list.(*FormalArgList),
				ItemDollar[6].node.(*TokenNode), ItemDollar[7].node.(*TokenNode), ItemDollar[8].node.(*StmtBlockNode))
		}
	case 42:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:200
		{
			fallback := NewPrimaryNode(setPos(ItemDollar[2].pos), "()", TypeID)
			tmp := NewFormalArgList(nil, nil)
			ItemVAL.node = NewFunctionDefNode(setPos(ItemDollar[1].pos), fallback, tmp,
				ItemDollar[3].node.(*TokenNode), ItemDollar[4].node.(*TokenNode), ItemDollar[5].node.(*StmtBlockNode))
		}
	case 43:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:207
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeID)
		}
	case 44:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:208
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeHEX)
		}
	case 45:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:210
		{
			ItemVAL.list = NewFormalArgList(ItemDollar[1].list.(*FormalArgList), ItemDollar[3].node.(*FormalArgNode))
		}
	case 46:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:213
		{
			ItemVAL.list = NewFormalArgList(nil, ItemDollar[1].node.(*FormalArgNode))
		}
	case 47:
		ItemDollar = ItemS[Itempt-0 : Itempt+1]
//line parser.go.y:216
		{
			ItemVAL.list = NewFormalArgList(nil, nil)
		}
	case 48:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:221
		{
			tmp := NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeID)
			ItemVAL.node = NewFormalArgNode(ItemDollar[1].node.(*TypeNameNode), tmp)
		}
	case 49:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:225
		{
			tmp := NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeID)
			if ItemDollar[1].node.(*LvalueNode).LvalueType == TypePrimary { //LA(1) makes trouble when two IDs occurs in a row
				ItemDollar[1].node.(*LvalueNode).Change(prevBuffer.val)
			}
			ItemVAL.node = NewFormalArgNode(NewTypeNameNode(NewLibraryTypeNode(ItemDollar[1].node.(*LvalueNode), false, false)), tmp)
		}
	case 50:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:232
		{
			tmp := NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeID)
			ItemVAL.node = NewFormalArgNode(nil, tmp)
		}
	case 51:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:238
		{
			ItemVAL.node = NewBasicTypeNode(setPos(buffer.pos), buffer.val, TypeUINT)
		}
	case 52:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:239
		{
			ItemVAL.node = NewBasicTypeNode(setPos(buffer.pos), buffer.val, TypeINT)
		}
	case 53:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:240
		{
			ItemVAL.node = NewBasicTypeNode(setPos(buffer.pos), buffer.val, TypeBYTE)
		}
	case 54:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:241
		{
			ItemVAL.node = NewBasicTypeNode(setPos(buffer.pos), buffer.val, TypeADDRESS)
		}
	case 55:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:242
		{
			ItemVAL.node = NewBasicTypeNode(setPos(buffer.pos), buffer.val, TypeSTRING)
		}
	case 56:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:243
		{
			ItemVAL.node = NewBasicTypeNode(setPos(buffer.pos), buffer.val, TypeARRAY)
		}
	case 57:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:244
		{
			ItemVAL.node = NewBasicTypeNode(setPos(buffer.pos), buffer.val, TypeBOOL)
		}
	case 58:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:245
		{
			ItemVAL.node = NewBasicTypeNode(setPos(buffer.pos), buffer.val, TypeFUNCTION)
		}
	case 59:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:247
		{
			ItemVAL.node = NewBasicTypeNode(setPos(buffer.pos), buffer.val, TypeSTRUCT)
		}
	case 60:
		ItemDollar = ItemS[Itempt-6 : Itempt+1]
//line parser.go.y:249
		{
			ItemVAL.node = NewMapTypeNode(setPos(ItemDollar[1].pos), ItemDollar[3].node.(*BasicTypeNode), ItemDollar[5].node.(*TypeNameNode))
		}
	case 61:
		ItemDollar = ItemS[Itempt-8 : Itempt+1]
//line parser.go.y:252
		{
			ItemVAL.node = NewMapTypeNode(setPos(ItemDollar[1].pos), ItemDollar[3].node.(*BasicTypeNode), ItemDollar[6].node.(*TypeNameNode))
		}
	case 62:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:256
		{
			ItemVAL.node = NewStructArgTypeNode(setPos(buffer.pos), ItemDollar[2].list.(*TypeNameList))
		}
	case 63:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:261
		{
			ItemVAL.node = NewTypeNameNode(ItemDollar[1].node)
		}
	case 64:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:264
		{
			ItemVAL.node = NewTypeNameNode(ItemDollar[1].node)
		}
	case 65:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:267
		{
			ItemVAL.node = NewTypeNameNode(ItemDollar[1].node)
		}
	case 66:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:270
		{
			ItemVAL.node = NewTypeNameNode(ItemDollar[1].node)
		}
	case 67:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:273
		{
			ItemVAL.node = NewTypeNameNode(NewArrayTypeNode(ItemDollar[1].node.(*TypeNameNode), nil, false))
		}
	case 68:
		ItemDollar = ItemS[Itempt-4 : Itempt+1]
//line parser.go.y:276
		{
			ItemVAL.node = NewTypeNameNode(NewArrayTypeNode(ItemDollar[1].node.(*TypeNameNode), nil, true))
		}
	case 69:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:279
		{
			ItemVAL.node = NewTypeNameNode(NewArrayTypeNode(ItemDollar[1].node.(*TypeNameNode), ItemDollar[2].node.(*AllocSizeNode), false))
		}
	case 70:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:282
		{
			ItemVAL.node = NewTypeNameNode(NewLibraryTypeNode(ItemDollar[1].node.(*LvalueNode), false, true))
		}
	case 71:
		ItemDollar = ItemS[Itempt-4 : Itempt+1]
//line parser.go.y:285
		{
			ItemVAL.node = NewTypeNameNode(NewLibraryTypeNode(ItemDollar[1].node.(*LvalueNode), true, true))
		}
	case 72:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:289
		{
			ItemVAL.list = NewTypeNameList(ItemDollar[1].list.(*TypeNameList), ItemDollar[3].node.(*TypeNameNode))
		}
	case 73:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:292
		{
			ItemVAL.list = NewTypeNameList(nil, ItemDollar[1].node.(*TypeNameNode))
		}
	case 74:
		ItemDollar = ItemS[Itempt-0 : Itempt+1]
//line parser.go.y:295
		{
			ItemVAL.list = NewTypeNameList(nil, nil)
		}
	case 75:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:299
		{
			ItemVAL.node = NewStmtBlockNode(ItemDollar[2].list.(*StmtList))
		}
	case 76:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:301
		{
			ItemVAL.list = NewStmtList(ItemDollar[1].list.(*StmtList), ItemDollar[2].node.(*StmtNode))
		}
	case 77:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:304
		{
			ItemVAL.list = NewStmtList(nil, ItemDollar[1].node.(*StmtNode))
		}
	case 78:
		ItemDollar = ItemS[Itempt-0 : Itempt+1]
//line parser.go.y:307
		{
			ItemVAL.list = NewStmtList(nil, nil)
		}
	case 79:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:311
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 80:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:312
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 81:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:313
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 82:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:314
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 83:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:315
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 84:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:316
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 85:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:317
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 86:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:318
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 87:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:319
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 88:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:320
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 89:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:321
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 90:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:322
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 91:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:323
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 92:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:324
		{
			ItemVAL.node = NewStmtNode(ItemDollar[1].node)
		}
	case 93:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:325
		{
			ItemVAL.node = NewStmtNode(NewTokenNode(setPos(buffer.pos), buffer.val))
		}
	case 94:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:328
		{
			ItemVAL.node = NewIfStmtNode(ItemDollar[1].node.(*IfNode), ItemDollar[2].list.(*ElseIfList), ItemDollar[3].node.(*ElseNode))
		}
	case 95:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:331
		{
			ItemVAL.node = NewIfStmtNode(ItemDollar[1].node.(*IfNode), ItemDollar[2].list.(*ElseIfList), nil)
		}
	case 96:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:334
		{
			ItemVAL.node = NewIfStmtNode(ItemDollar[1].node.(*IfNode), nil, ItemDollar[2].node.(*ElseNode))
		}
	case 97:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:337
		{
			ItemVAL.node = NewIfStmtNode(ItemDollar[1].node.(*IfNode), nil, nil)
		}
	case 98:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:341
		{
			ItemVAL.node = NewIfNode(setPos(ItemDollar[1].pos), ItemDollar[3].node.(*ExpressionNode), ItemDollar[5].node.(*StmtBlockNode))
		}
	case 99:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:345
		{
			ItemVAL.node = NewElseNode(setPos(ItemDollar[1].pos), ItemDollar[2].node.(*StmtBlockNode))
		}
	case 100:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:349
		{
			ItemVAL.list = NewElseIfList(ItemDollar[1].list.(*ElseIfList), ItemDollar[2].node.(*ElseIfNode))
		}
	case 101:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:352
		{
			ItemVAL.list = NewElseIfList(nil, ItemDollar[1].node.(*ElseIfNode))
		}
	case 102:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:356
		{
			ItemVAL.node = NewElseIfNode(setPos(ItemDollar[1].pos), ItemDollar[3].node.(*ExpressionNode), ItemDollar[5].node.(*StmtBlockNode))
		}
	case 103:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:361
		{
			ItemVAL.node = NewWhileNode(setPos(ItemDollar[1].pos), ItemDollar[3].node.(*ExpressionNode), ItemDollar[5].node.(*StmtNode))
		}
	case 104:
		ItemDollar = ItemS[Itempt-7 : Itempt+1]
//line parser.go.y:365
		{
			ItemVAL.node = NewDoWhileNode(setPos(ItemDollar[1].pos), ItemDollar[2].node.(*StmtNode), ItemDollar[5].node.(*ExpressionNode))
		}
	case 105:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:368
		{
			ItemVAL.node = NewContinueStmtNode(setPos(ItemDollar[1].pos))
		}
	case 106:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:371
		{
			ItemVAL.node = NewBreakStmtNode(setPos(ItemDollar[1].pos))
		}
	case 107:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:375
		{
			ItemVAL.node = NewReturnStmtNode(setPos(ItemDollar[1].pos), ItemDollar[3].list.(*ExpressionList))
		}
	case 108:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:378
		{
			ItemVAL.node = NewReturnStmtNode(setPos(ItemDollar[1].pos), ItemDollar[2].list.(*ExpressionList))
		}
	case 109:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:382
		{
			//requireArgs : expression ',' ID | expression ',' MESSAGE | expression
			ItemVAL.node = NewRequireStmtNode(setPos(ItemDollar[1].pos), ItemDollar[3].list.(*ExpressionList))
		}
	case 110:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:387
		{
			ItemVAL.node = NewThrowStmtNode(setPos(ItemDollar[1].pos), ItemDollar[3].list.(*ExpressionList))
		}
	case 111:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:391
		{
			ItemVAL.node = NewEmitStmtNode(setPos(ItemDollar[1].pos), ItemDollar[2].node.(*SubexprNode))
		}
	case 112:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:395
		{
			ItemVAL.node = NewGotoStmtNode(setPos(ItemDollar[1].pos), ItemDollar[2].node.(*PrimaryList))
		}
	case 113:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:398
		{
			ItemVAL.node = NewGotoStmtNode(setPos(ItemDollar[1].pos), ItemDollar[3].list.(*PrimaryList))
		}
	case 114:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:402
		{
			ItemVAL.list = NewPrimaryList(ItemDollar[1].list.(*PrimaryList), ItemDollar[3].node.(*PrimaryList).Get(0))
		}
	case 115:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:405
		{
			ItemVAL.list = ItemDollar[1].node.(*PrimaryList)
		}
	case 116:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:409
		{
			tmp := NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeHEX)
			ItemVAL.node = NewPrimaryList(nil, tmp)
		}
	case 117:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:413
		{
			tmp := NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeGOTOADDRESS)
			ItemVAL.node = NewPrimaryList(nil, tmp)
		}
	case 118:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:417
		{ //MESSAGE must be '0x...'
			tmp := NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeMESSAGE)
			ItemVAL.node = NewPrimaryList(nil, tmp)
		}
	case 119:
		ItemDollar = ItemS[Itempt-4 : Itempt+1]
//line parser.go.y:421
		{
			ItemVAL.node = NewCalcAssignStmtNode(ItemDollar[1].node.(*LvalueNode), ItemDollar[2].val, ItemDollar[3].node.(*ExpressionNode))
		}
	case 120:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:424
		{
			ItemVAL.node = NewExprStmtNode(ItemDollar[1].node.(*ExpressionNode))
		}
	case 121:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:427
		{
			ItemVAL.node = NewFallbackStmtNode(setPos(ItemDollar[1].pos))
		}
	case 122:
		ItemDollar = ItemS[Itempt-4 : Itempt+1]
//line parser.go.y:432
		{
			ItemVAL.node = NewCastExpressionNode(ItemDollar[1].node.(*TypeNameNode), ItemDollar[3].node.(*ExpressionNode))
		}
	case 123:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:436
		{
			ItemDollar[3].val = buffer.val
		}
	case 124:
		ItemDollar = ItemS[Itempt-7 : Itempt+1]
//line parser.go.y:436
		{ //distinguish call & staticcall from ID
			//lvalue => castExpression | ID | HEX | MSGSENDER
			ItemVAL.node = NewExternalCallExprNode(ItemDollar[1].node.(*LvalueNode), ItemDollar[3].val, ItemDollar[6].list.(*ExpressionList))
		}
	case 125:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:441
		{
			ItemVAL.list = NewExtSpecifierList(ItemDollar[1].node.(*ExtSpecifierNode), ItemDollar[2].node.(*ExtSpecifierNode))
		}
	case 126:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:444
		{
			ItemVAL.list = NewExtSpecifierList(ItemDollar[1].node.(*ExtSpecifierNode), nil)
		}
	case 127:
		ItemDollar = ItemS[Itempt-0 : Itempt+1]
//line parser.go.y:447
		{
			ItemVAL.list = NewExtSpecifierList(nil, nil)
		}
	case 128:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:451
		{
			ItemDollar[2].val = buffer.val
		}
	case 129:
		ItemDollar = ItemS[Itempt-6 : Itempt+1]
//line parser.go.y:451
		{
			ItemVAL.node = NewExtSpecifierNode(ItemDollar[2].val, ItemDollar[5].node.(*ExpressionNode))
		}
	case 130:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:456
		{
			ItemVAL.list = ItemDollar[1].list
		}
	case 131:
		ItemDollar = ItemS[Itempt-0 : Itempt+1]
//line parser.go.y:457
		{
			ItemVAL.list = NewExpressionList(nil, nil)
		}
	case 132:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:461
		{
			ItemVAL.list = NewExpressionList(ItemDollar[1].list.(*ExpressionList), ItemDollar[3].node.(*ExpressionNode))
		}
	case 133:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:464
		{
			ItemVAL.list = NewExpressionList(nil, ItemDollar[1].node.(*ExpressionNode))
		}
	case 134:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:468
		{
			ItemVAL.val = "+="
		}
	case 135:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:468
		{
			ItemVAL.val = "-="
		}
	case 136:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:468
		{
			ItemVAL.val = "*="
		}
	case 137:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:468
		{
			ItemVAL.val = "/="
		}
	case 138:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:469
		{
			ItemVAL.val = "=="
		}
	case 139:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:469
		{
			ItemVAL.val = "!="
		}
	case 140:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:470
		{
			ItemVAL.val = "<"
		}
	case 141:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:470
		{
			ItemVAL.val = ">"
		}
	case 142:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:470
		{
			ItemVAL.val = "<="
		}
	case 143:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:470
		{
			ItemVAL.val = ">="
		}
	case 144:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:471
		{
			ItemVAL.val = "<<"
		}
	case 145:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:471
		{
			ItemVAL.val = ">>"
		}
	case 146:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:472
		{
			ItemVAL.val = "+"
		}
	case 147:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:472
		{
			ItemVAL.val = "-"
		}
	case 148:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:473
		{
			ItemVAL.val = "*"
		}
	case 149:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:473
		{
			ItemVAL.val = "/"
		}
	case 150:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:473
		{
			ItemVAL.val = "%"
		}
	case 151:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:474
		{
			ItemVAL.val = "**"
		}
	case 152:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:476
		{
			ItemVAL.node = NewExpressionNode(ItemDollar[1].node.(*SubexprNode))
		}
	case 153:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:478
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 154:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:479
		{
			ItemVAL.node = NewAssignExprNode(ItemDollar[1].list.(*ExpressionList), ItemDollar[3].node.(*SubexprNode))
		}
	case 155:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:483
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 156:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:484
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), "||", ItemDollar[3].node.(*SubexprNode))
		}
	case 157:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:488
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 158:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:489
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), "&&", ItemDollar[3].node.(*SubexprNode))
		}
	case 159:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:493
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 160:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:494
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), ItemDollar[2].val, ItemDollar[3].node.(*SubexprNode))
		}
	case 161:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:498
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 162:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:499
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), ItemDollar[2].val, ItemDollar[3].node.(*SubexprNode))
		}
	case 163:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:503
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 164:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:504
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), "|", ItemDollar[3].node.(*SubexprNode))
		}
	case 165:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:508
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 166:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:509
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), "^", ItemDollar[3].node.(*SubexprNode))
		}
	case 167:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:513
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 168:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:514
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), "&", ItemDollar[3].node.(*SubexprNode))
		}
	case 169:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:518
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 170:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:519
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), ItemDollar[2].val, ItemDollar[3].node.(*SubexprNode))
		}
	case 171:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:523
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 172:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:524
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), ItemDollar[2].val, ItemDollar[3].node.(*SubexprNode))
		}
	case 173:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:528
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 174:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:529
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), ItemDollar[2].val, ItemDollar[3].node.(*SubexprNode))
		}
	case 175:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:533
		{
			ItemVAL.node = ItemDollar[1].node
		}
	case 176:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:534
		{
			ItemVAL.node = NewOpExprNode(ItemDollar[1].node.(*SubexprNode), ItemDollar[2].val, ItemDollar[3].node.(*SubexprNode))
		}
	case 177:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:538
		{
			ItemVAL.node = NewUnaryExprNode("+", ItemDollar[2].node.(*RvalueNode))
		}
	case 178:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:541
		{
			ItemVAL.node = NewUnaryExprNode("-", ItemDollar[2].node.(*RvalueNode))
		}
	case 179:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:544
		{
			ItemVAL.node = NewUnaryExprNode("!", ItemDollar[2].node.(*RvalueNode))
		}
	case 180:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:547
		{
			ItemVAL.node = NewUnaryExprNode("~", ItemDollar[2].node.(*RvalueNode))
		}
	case 181:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:550
		{
			ItemVAL.node = NewUnaryExprNode("", ItemDollar[1].node.(*RvalueNode))
		}
	case 182:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:555
		{
			ItemVAL.node = NewAllocRvalueNode(ItemDollar[2].node.(*CastExpressionNode))
		}
	case 183:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:558
		{
			ItemVAL.node = NewCallRvalueNode(ItemDollar[1].node.(*ExternalCallExprNode), ItemDollar[2].list.(*ExtSpecifierList))
		}
	case 184:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:561
		{
			ItemVAL.node = NewRvalueNode(ItemDollar[1].node.(*LvalueNode))
		}
	case 185:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:566
		{
			ItemVAL.node = NewMemAllocNode(ItemDollar[2].node.(*AllocSizeNode))
		}
	case 186:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:569
		{
			ItemVAL.node = NewStorageAllocNode(ItemDollar[2].node.(*AllocSizeNode))
		}
	case 187:
		ItemDollar = ItemS[Itempt-2 : Itempt+1]
//line parser.go.y:572
		{
			ItemVAL.node = NewLvalueAllocNode(ItemDollar[1].node.(*LvalueNode), ItemDollar[2].node.(*AllocSizeNode))
		}
	case 188:
		ItemDollar = ItemS[Itempt-4 : Itempt+1]
//line parser.go.y:575
		{ //all or none for typeName
			ItemVAL.node = NewFuntionCallNode(ItemDollar[1].node.(*LvalueNode), ItemDollar[3].list.(*ExpressionList))
		}
	case 189:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:578
		{
			ItemVAL.node = NewMemberAccessNode(ItemDollar[1].node.(*LvalueNode), buffer.val)
		}
	case 190:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:581
		{
			ItemVAL.node = NewMemberAccessNode(ItemDollar[1].node.(*LvalueNode), "this")
		}
	case 191:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:584
		{
			ItemVAL.node = NewPrimaryLvalueNode(ItemDollar[1].node.(*PrimaryNode))
		}
	case 192:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:587
		{
			ItemVAL.node = NewCastLvalueNode(ItemDollar[1].node.(*CastExpressionNode))
		}
	case 193:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:590
		{
			ItemVAL.node = NewExprLvalueNode(ItemDollar[2].node.(*ExpressionNode))
		}
	case 194:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:593
		{
			ItemVAL.node = NewTypeLvalueNode(ItemDollar[1].node.(*TypeNameNode))
		}
	case 195:
		ItemDollar = ItemS[Itempt-3 : Itempt+1]
//line parser.go.y:598
		{
			ItemVAL.node = NewAllocSizeNode(ItemDollar[2].node.(*ExpressionNode), nil, nil)
		}
	case 196:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:601
		{ //ID must be 'len'
			ItemVAL.node = NewAllocSizeNode(ItemDollar[2].node.(*ExpressionNode), ItemDollar[4].node.(*ExpressionNode), nil)
		}
	case 197:
		ItemDollar = ItemS[Itempt-5 : Itempt+1]
//line parser.go.y:604
		{
			ItemVAL.node = NewAllocSizeNode(ItemDollar[2].node.(*ExpressionNode), nil, ItemDollar[4].node.(*ExpressionNode))
		}
	case 198:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:609
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeBOOLLITERAL)
		}
	case 199:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:610
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeNUM)
		}
	case 200:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:611
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeHEX)
		}
	case 201:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:612
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeMESSAGE)
		}
	case 202:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:613
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeMSGVAL)
		}
	case 203:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:614
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeMSGDATA)
		}
	case 204:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:615
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeMSGGAS)
		}
	case 205:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:616
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeMSGSENDER)
		}
	case 206:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:617
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeTHIS)
		}
	case 207:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:618
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeID)
		}
	case 208:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:619
		{
			ItemVAL.node = NewPrimaryNode(setPos(buffer.pos), buffer.val, TypeNA)
		}
	case 209:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:622
		{
			ItemVAL.node = NewTokenNode(setPos(buffer.pos), buffer.val)
		}
	case 210:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:623
		{
			ItemVAL.node = NewTokenNode(setPos(buffer.pos), buffer.val)
		}
	case 211:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:625
		{
			ItemVAL.node = NewTokenNode(setPos(buffer.pos), buffer.val)
		}
	case 212:
		ItemDollar = ItemS[Itempt-1 : Itempt+1]
//line parser.go.y:626
		{
			ItemVAL.node = NewTokenNode(setPos(buffer.pos), buffer.val)
		}
	case 213:
		ItemDollar = ItemS[Itempt-0 : Itempt+1]
//line parser.go.y:627
		{
			ItemVAL.node = NewTokenNode(NewPos(0, 0), "")
		}
	}
	goto Itemstack /* stack new state and value */
}
